---
- name: Configure RiderHub Flarum Application
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    project_name: "riderhub"
    php_version: "8.1"
    composer_home: "/tmp/composer"
    
  roles:
    - riderhub
