---
- name: Install Composer dependencies
  shell: |
    cd src/{{ project_name }}
    composer install --no-dev --optimize-autoloader --no-interaction
  args:
    creates: "src/{{ project_name }}/vendor/autoload.php"
  
- name: Configure Flarum for DynamoDB
  template:
    src: config.php.j2
    dest: "src/{{ project_name }}/config.php"
    mode: '0644'
  vars:
    dynamodb_posts_table: "{{ dynamodb_posts_table | default('riderhub-posts') }}"
    dynamodb_comments_table: "{{ dynamodb_comments_table | default('riderhub-comments') }}"
    s3_media_bucket: "{{ s3_media_bucket | default('riderhub-media') }}"
    aws_region: "{{ aws_region | default('us-east-1') }}"
    app_url: "{{ app_url | default('https://riderhub.amplifyapp.com') }}"
    app_env: "{{ app_env | default('production') }}"
    app_debug: "{{ app_debug | default('false') }}"
    
- name: Set up DynamoDB adapter
  shell: |
    cd src/{{ project_name }}
    composer require aws/aws-sdk-php
    composer require bref/bref
  args:
    creates: "src/{{ project_name }}/vendor/aws/aws-sdk-php"
    
- name: Create Lambda handler
  template:
    src: lambda.php.j2
    dest: "src/{{ project_name }}/lambda.php"
    mode: '0644'
  vars:
    dynamodb_posts_table: "{{ dynamodb_posts_table | default('riderhub-posts') }}"
    dynamodb_comments_table: "{{ dynamodb_comments_table | default('riderhub-comments') }}"
    s3_media_bucket: "{{ s3_media_bucket | default('riderhub-media') }}"
    aws_region: "{{ aws_region | default('us-east-1') }}"
    app_url: "{{ app_url | default('https://riderhub.amplifyapp.com') }}"
    app_env: "{{ app_env | default('production') }}"
    app_debug: "{{ app_debug | default('false') }}"
    
- name: Optimize for production
  shell: |
    cd src/{{ project_name }}
    php flarum cache:clear || true
    php flarum assets:publish || true
  ignore_errors: true
